apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-ec2-provisioning
  description: Backstage EC2 provisioning using Terraform and GitHub Actions
  annotations:
    github.com/project-slug: sunil566/backstage-ec2-provisioning
spec:
  type: service
  lifecycle: experimental
  owner: user:default/sunil566
