apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: aws-ec2-provisioning
  title: AWS EC2 Provisioning
  description: Create an EC2 Terraform repository and deploy an EC2 instance with GitHub Actions
  tags:
    - aws
    - ec2
    - terraform
    - github-actions

spec:
  owner: user:default/sunil566
  type: service

  parameters:
    - title: EC2 Configuration
      required:
        - repoName
        - instanceName
        - instanceType
        - amiId
        - subnetId
        - securityGroupId
      properties:
        repoName:
          title: GitHub repository name
          type: string
          description: Repository that Backstage will create
          default: ec2-demo

        instanceName:
          title: EC2 instance name
          type: string
          default: backstage-ec2

        instanceType:
          title: EC2 instance type
          type: string
          default: t3.micro

        amiId:
          title: AMI ID
          type: string
          description: Use an AMI valid for your AWS region

        subnetId:
          title: Subnet ID
          type: string

        securityGroupId:
          title: Security Group ID
          type: string

        awsRegion:
          title: AWS Region
          type: string
          default: ap-south-1

  steps:
    - id: fetch
      name: Generate Terraform repository
      action: fetch:template
      input:
        url: ./skeleton
        values:
          instanceName: ${{ parameters.instanceName }}
          instanceType: ${{ parameters.instanceType }}
          amiId: ${{ parameters.amiId }}
          subnetId: ${{ parameters.subnetId }}
          securityGroupId: ${{ parameters.securityGroupId }}
          awsRegion: ${{ parameters.awsRegion }}
          owner: ${{ user.entity.metadata.name }}

    - id: publish
      name: Create GitHub repository
      action: publish:github
      input:
        allowedHosts:
          - github.com
        repoUrl: github.com?owner=sunil566&repo=${{ parameters.repoName }}
        description: EC2 infrastructure generated by Backstage
        defaultBranch: main

    - id: output
      name: Repository
      action: debug:log
      input:
        message: "Created repository for EC2 provisioning."

  output:
    links:
      - title: GitHub Repository
        url: https://github.com/sunil566/${{ parameters.repoName }}
